#!/bin/bash

VMID="$1"
ACTION="$2"
SLEPT=""

vmpid() {
  cat "/var/run/qemu-server/$VMID.pid"
}

if_action() {
  if [[ "$ACTION" == "$1" ]]; then
    shift
    eval "$@"
  fi
}

sleep_once() {
  if [[ -z "$SLEPT" ]]; then
    sleep 1s
    SLEPT=1
  fi
}

hostpci_ids() {
  grep '^hostpci[0-9]:.*0000' "/etc/pve/qemu-server/$VMID.conf" | awk '{print $2}' | awk -F, '{print $1}'
}

exec_pci_rescan() {
  echo "Running PCI rescan for $VMID..."
  echo 1 > /sys/bus/pci/rescan
}

exec_set_haltpoll() {
  echo "Setting haltpoll for $VMID..."
  echo $1 > /sys/module/kvm/parameters/halt_poll_ns
}

exec_assign_interrupts() {
  local SLEEP="30s"
  if [[ $1 == --sleep=* ]]; then
    SLEEP="${1#--sleep=}"
    shift
  fi

  echo "Wating $SLEEP seconds for all vfio-gpu interrupts to show up..."
  sleep "$SLEEP"

  MASK="$1"
  shift

  if [[ "$1" == "--all" ]]; then
    set -- $(hostpci_ids)
  fi

  for interrupt; do
    interrupt=$(printf '%b' "${interrupt//%/\\x}")
    echo "Moving $interrupt interrupts to $MASK cpu cores $VMID..."
    grep "$interrupt" /proc/interrupts | cut -d ":" -f 1 | while read -r i; do
      echo "- IRQ: $(grep "^\s*$i:" /proc/interrupts)"
      echo "$MASK" > /proc/irq/$i/smp_affinity_list
    done
  done
}

exec_pci_unbind() {
  if [[ "$1" == "--all" ]]; then
    set -- $(hostpci_ids)
  else
    set -- "0000:$1:$2.$3"
  fi

  for devid; do
    if [[ -e "/sys/bus/pci/devices/$devid" ]]; then
      echo "Running PCI unbind of '$devid' for $VMID..."
      echo 1 > "/sys/bus/pci/devices/$devid/remove"
    elif [[ -e "/sys/bus/pci/devices/$devid.0" ]]; then
      echo "Running PCI unbind of '$devid.0' for $VMID..."
      echo 1 > "/sys/bus/pci/devices/$devid.0/remove"
    else
      echo "The '$devid' not found in '/sys/bus/pci/devices'"
    fi
  done
}

exec_cpu_taskset() {
  sleep_once

  echo "Running taskset with $1 for $(vmpid)..."
  taskset -a -p -c "$1" "$(vmpid)"
  echo ""
}

exec_cpu_chrt() {
  sleep_once

  echo "Running chrt with $1:$2 for $(vmpid)..."
  chrt -v "--$1" -a -p "$2" "$(vmpid)"
  echo ""
}

exec_qm_conflict() {
  echo "Conflicting with other VM$1, shutdown just in case..."
  qm shutdown "$1"
}

exec_qm_depends() {
  echo "VM$1 is required, ensure that it is started..."
  qm start "$1"
}

exec_cmds() {
  while read CMD ARG1 ARG2 ARG3 REST; do
    case "$CMD" in
      "#pci_remove")
        if_action pre-start exec_pci_unbind "$ARG1" "$ARG2" "$ARG3"
        ;;

      "#pci_rescan")
        if_action pre-start exec_pci_rescan
        ;;

      "#cpu_taskset")
        if_action post-start exec_cpu_taskset "$ARG1"
        ;;

      "#set_halt_poll")
        if_action post-start exec_set_haltpoll "$ARG1"
        ;;

      "#assign_interrupts")
        if_action post-start exec_assign_interrupts "$ARG1" "$ARG2" "$ARG3" $REST
        ;;

      "#cpu_chrt")
        if_action post-start exec_cpu_chrt "${ARG1:-fifo}" "${ARG2:-1}"
        ;;

      "#qm_depends")
        if_action post-start exec_qm_depends "$ARG1"
        ;;

      "#pci_unbind")
        if_action post-stop exec_pci_unbind "$ARG1" "$ARG2" "$ARG3"
        ;;

      "#pci_unbind_all")
        if_action post-stop exec_pci_unbind_all
        ;;

      "#pci_rebind")
        if_action post-stop exec_pci_rescan
        ;;

      "#qm_conflict")
        if_action pre-start exec_qm_conflict "$ARG1"
        ;;

      "#qm_*"|"#cpu_*"|"#pci_*"|"#set_*"|"#assign_*")
        echo "exec-cmds: command is unknown '$CMD'"
        ;;
    esac
  done
}

echo "Running exec-cmds for $VMID on $ACTION..."

exec_cmds < "/etc/pve/qemu-server/$VMID.conf"

exit 0
